server:
  port: 5950
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:3090/eureka
spring:
  application:
    name: micro-config
  cloud:
    config:
      server:
        git:
          uri: http
          force-pull: true  #强制拉去
#测试上线用的
